rsync -auv ./doc parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -auv ./editor parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -auv ./html parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -auv ./js parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -auv ./images parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -auv ./node parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
#rsync -auv ./node_modules parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -auv ./style parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -auv ./systemcall parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./tools/ffmpeg* parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs/tools
rsync -ptoguv ./tools/node* parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs/tools
rsync -ptoguv ./tools/ffprob* parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs/tools
rsync -ptoguv ./tools/fonts.conf parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs/tools
rsync -auv  ./tools/presets parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs/tools
rsync -auv  ./tools/java* parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs/tools
rsync -ptoguv ./tools/teicorpo.jar parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs/tools
rsync -ptoguv ./transcriberjs*.nsi parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./index.js parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./README.md parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./trjslocal.html parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./gulpfile.js parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./renderer.js parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./trjsclient.html parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./trjsread.html parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./index.html parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./LICENSE.md parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./package.json parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./trjsdistant.html parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./*.sh parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
rsync -ptoguv ./*.bat parisse@ct3.ortolang.fr:/applis/devlopt/betatrjs
